### ISSUE TITLE
Motion will not send a Notification with Picture

### ISSUE THREAD

**Issue by djnews24** [rxseger/homebridge-camera-motion#6]
A motion is detected but no notification with lastsnap will shown.
Camera is in the same home kit room

**Comment by willwade** [comment]
Me too. ~~Could it be a permissions thing? (Nb the example config needed changing for me to reference the snapshot at /var/lib/motion/)~~ Update: On second thoughts is it not this thats waiting to get merged: https://github.com/rxseger/homebridge-camera-motion/pull/7 ?

**Comment by cbarratt** [comment]
Same here, the plugin logs that a snapshot is detected but no homekit notification is sent.

```
Apr  5 10:58:43 DietPi motion: [1] [NTC] [EVT] event_newfile: File of type 2 saved to: /security/03-20170405105842-snapshot.jpg
Apr  5 10:58:43 DietPi homebridge[1654]: got from pipe: |/security/03-20170405105842-snapshot.jpg#0112#01103#011542#011184#011677#01192#01113#0115557
Apr  5 10:58:43 DietPi homebridge[1654]: |
Apr  5 10:58:43 DietPi homebridge[1654]: filename is /security/03-20170405105842-snapshot.jpg
```

**Comment by djnews24** [comment]
Found the Solution https://github.com/jspv/HAP-NodeJS/commit/932ef587bee27cd3788c066d52cfd559ab556b3a#diff-00b357729430bdec42cba36540307f8a
